### ISSUE TITLE
Add a module system

### ISSUE THREAD

**Issue by Antafes** [friend8/SmartWork#3]
Add a module system to easily add modules like login or registration.
- [x] Modules can be added directly from SmartWork or from the page that is using this framework
- [x] As a default, the index and imprint module will be loaded
- [x] Needs an option to disable the module usage, mainly for backwards compatibility
- Each module may contain the following elements:
  - [x] Page
  - [x] Db migrations
  - [x] Models
  - [x] Lists
  - [x] Utilities
- [x] Which modules are loaded, will be defined in the config files
- [x] Adjust the db_migrations table to work with multiple locations of the migration files
- [x] Adjust the auto loader to work with the modules
  - load order: page using the framework -> modules on the page -> SmartWork -> SmartWork modules
  - The namespace in modules should begin as following:
    - for Smartwork: SmartWork/MyModule
    - for the page using the framework: MyModule
- [x] Dynamically create the menu

**Comment by friend8** [comment]
- Modules can be added directly from SmartWork or from the page that is using this framework
- As a default, the index and imprint module will be loaded
- Needs an option to disable the module usage, mainly for backwards compatibility
- Each module may contain the following elements:
 - Page
 - Db migrations
 - Models
 - Lists
 - Utilities
